### ISSUE TITLE
Submission error

### ISSUE THREAD

**Issue by elenaermakova** [umanlp/tg2019task#9]
I created ZIP file containing prediction.txt. Trying to make a submit, I got the following error. What can be the reason for that?
```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
 File "/tmp/codalab/tmp5PJhCI/run/program/evaluate_codalab.py", line 48, in
   main()
 File "/tmp/codalab/tmp5PJhCI/run/program/evaluate_codalab.py", line 37, in main
   gold, pred = load_gold(gold_filename), load_pred(pred_filename)
 File "/tmp/codalab/tmp5PJhCI/run/program/evaluate.py", line 38, in load_pred
   df = pd.read_csv(filepath_or_buffer, sep=sep, names=('question', 'explanation'))
 File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 709, in parser_f
   return _read(filepath_or_buffer, kwds)
 File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 449, in _read
   parser = TextFileReader(filepath_or_buffer, **kwds)
 File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 818, in __init__
   self._make_engine(self.engine)
 File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1049, in _make_engine
   self._engine = CParserWrapper(self.f, **self.options)
 File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1695, in __init__
   self._reader = parsers.TextReader(src, **kwds)
 File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
 File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/tmp/codalab/tmp5PJhCI/run/input/res/predict.txt' does not exist
```

**Comment by dustalov** [comment]
CodaLab requires you to use the exact filename, `predict.txt`, for the prediction output in your submission (see the [instruction](https://github.com/umanlp/tg2019task#python)). Please try again by uploading the ZIP archive containing the `predict.txt` file.
